### ISSUE TITLE
Simplify install instructions

### ISSUE THREAD

**Issue by dolmen** [jupyter-xeus/xeus-sqlite#107]
I just want to access my SQLite database from a Jupyter notebook where I can directly use SQL queries.

This project looks interesting, but installation instructions look like to be for Jupyter experts.

I've never used Jupyter notebooks. I just installed jupyterlab on MacOS using `brew jupyterlab` and I can launch it using `jupyter lab`.
But now I would like to create an sqlite notbook.

The install instructions in the README mention "conda", but what is conda? I just want jupyterlab+xsqlite. I don't want to mess with the Python stack or any other snakes.

**Comment by marimeireles** [comment]
Hi @dolmen, thanks for the issue.
The instructions on the readme don't aim to cover all the possibilities on how to install the software, that'd be impossible for us to maintain. We're giving a working example of the recommended route. Unfortunately I can't test it on your env. or in an env. similar to yours to give you an answer, but if you're interested in adding your specific way of installing it to the docs, it will be very appreciated.
Conda is a package manager very similar to `brew` but it's OS agnostic. I'm recommending to use it because I believe the infrastructure that it offers is the best. (My opinion tho!)
I believe that if you build this project from source and install SQLite with brew it should work out of the box?
