### ISSUE TITLE
Kernel dies if no database is loaded

### ISSUE THREAD

**Issue by martinRenou** [jupyter-xeus/xeus-sqlite#17]
Accidentally removed the `examples.db` file, I noticed that running a command like `CREATE TABLE players (Name STRING, Class STRING, Level INTEGER)` results in the kernel dying. Maybe the issue should be catched and an error should be shown?

**Comment by marimeireles** [comment]
Yep! I've seen this happen. Good idea, will fix :)

**Comment by marimeireles** [comment]
This was also fixed on #40  .

**Comment by martinRenou** [comment]
Are you sure? I still this happen on master

**Comment by marimeireles** [comment]
Still happening. Thanks Martin.

**Comment by avinal** [comment]
I have backtracked this problem and I think a possible solution is to add a `nullptr` check for `m_db` here and modify error messages for commands
https://github.com/jupyter-xeus/xeus-sqlite/blob/566b14db8bc07aafdff6aeaa1b7a48b44d88ddd1/src/xeus_sqlite_interpreter.cpp#L398

### Assumptions
Let me walk you through the whole error:-
If it is a SQLite magic, more specifically `%LOAD`, this is handled by `if` part of the function `nl::json interpreter::execute_request_impl(...)` and variable `m_db` is initialized with a database connection pointer. What if database is not initialized 🤔 , this happens in two cases, first the magic SQLite is not `%LOAD` and second it is not a magic, in both cases `m_db` remains `nullptr` now, 
1. https://github.com/jupyter-xeus/xeus-sqlite/blob/566b14db8bc07aafdff6aeaa1b7a48b44d88ddd1/src/xeus_sqlite_interpreter.cpp#L398
Takes `m_db` as a param
2. https://github.com/jupyter-xeus/xeus-sqlite/blob/566b14db8bc07aafdff6aeaa1b7a48b44d88ddd1/src/xeus_sqlite_interpreter.cpp#L249
Creates `SQLite::Statement` object with `m_db` as a param
3. 
![image](https://user-images.githubusercontent.com/74113200/98857617-49107e00-2485-11eb-8274-a5802525c5b2.png)
https://github.com/SRombauts/SQLiteCpp/blob/adb7e7c489b0574a6c2f354ab14213bfb9dd4e49/src/Statement.cpp#L25
Initializes `mStmtPtr`, since `m_db` was `nullptr`, `m_db.getHandle()` returns an `null sqlite3*` pointer. `mStmtPtr` is a `Ptr` object now initialized to `nullptr`
4. 
![image](https://user-images.githubusercontent.com/74113200/98857758-8248ee00-2485-11eb-92d9-03b686aca917.png)
https://github.com/SRombauts/SQLiteCpp/blob/adb7e7c489b0574a6c2f354ab14213bfb9dd4e49/src/Statement.cpp#L354-L368
`sqlite3_prepare_v2` asumes that **The first argument, "db", is a database connection obtained from a prior successful call to sqlite3_open(), sqlite3_open_v2() or sqlite3_open16(). The database connection must not have been closed.**
[See sqlite official draft](https://www.sqlite.org/draft/capi3ref.html#sqlite3_prepare), but in our case `db` a.k.a `m_db` has not been passed through any sqlite calls and is still a `nullptr`. 

### Testing
To know the effects I wrote a script 
```cpp
#include <sqlite3.h>
#include <iostream>
int main(int argc, char const *argv[])
{
    sqlite3 *test;
    test = nullptr;
    int rc = sqlite3_prepare_v2(test, "DROP",4,nullptr,nullptr);
    std::cout<<rc;
    return 0;
}
```
Here are the result
![image](https://user-images.githubusercontent.com/74113200/98857295-e15a3300-2484-11eb-9c98-9f21b1ff7597.png)

This could have happened even at step 3 in `sqlite3_column_count` function. 

### More proof 
Just to check if removing `nullptr` solves the issue I modified the  code here https://github.com/jupyter-xeus/xeus-sqlite/blob/566b14db8bc07aafdff6aeaa1b7a48b44d88ddd1/src/xeus_sqlite_interpreter.cpp#L398 to this
```cpp
if(m_db!=nullptr)
{
    process_SQLite_input(execution_counter, m_db, code, xv_sqlite_df);
}
```
And kernel **did not die** in any of my test cases after this. This is not a solution just the core of the bug. A possible solution will be to always initialize `m_db` before performing any more queries. Please check all the points I showed above and run your own tests to confirm.

Hope this helps. Sorry for such a long comment 😅

**Comment by marimeireles** [comment]
Fixed by https://github.com/jupyter-xeus/xeus-sqlite/pull/116
