### ISSUE TITLE
Use Vega-Lite

### ISSUE THREAD

**Issue by domoritz** [jupyter-xeus/xeus-sqlite#48]
I’m excited to see that you use Vega for visualization and was wondering whether Vega-Lite would be a better fit. If you ran into issues, I’m happy to help.

**Comment by marimeireles** [comment]
Hey @domoritz thank you for getting in touch!
Vega-Lite would probably be a better fit, I had some problems with the interaction between json and javascript though, that's why I changed to Vega.
Our future plan is to write a package like [Altair](https://github.com/altair-viz/altair) but for C++, so we can have a generic way of using Vega through our C++ ecosystem.

> If you ran into issues, I’m happy to help.

Thanks a lot, I'll ping you! :)

**Comment by domoritz** [comment]
I would be curious to learn more about the issues you encountered. For context, Vega-Lite compiles to Vega and so I would expect that the interactions with JS would be the same.

**Comment by marimeireles** [comment]
Hey @domoritz, just to give you an update, we opted for two different uses of vega-lite.
One was developing this little [CRTP library](https://github.com/jupyter-xeus/xvega-bindings/) that's still very incomplete that kinda reimplements vega-lite syntax with a SQL flavor and the other is using a vega-lite json directly, like [this](https://github.com/jupyter-xeus/xeus-sql/blob/master/examples/XVega%20operations.ipynb) for example.
This was possible thanks to the work of @madhur-tandon by creating vega-lite bindings to C++ :)
Thanks for offering the help and cheers!

**Comment by domoritz** [comment]
Thanks for the update. Let me know if there is ever anything I can help with.
