### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by JohanMabille** [jupyter-xeus/xeus-sqlite#9]
Here are the remaining tasks before we can tag the first release:

- [X] Add kernel tests similar to those of [xeus-python](https://github.com/jupyter-xeus/xeus-python/blob/master/test/test_xeus_python_kernel.py)
- [X] Add documentation skeleton
- [x] Add an example notebook

**Comment by marimeireles** [comment]
Right, will work on it later today.
Thanks a lot for your work here @JohanMabille =)

**Comment by marimeireles** [comment]
Ugh, I just pushed everything to this repo instead of a copy of mine because it happens my personal remote also redirects to here. Super weird.
I didn't know that happened, never transferred a repo before, sorry.
I need help with docs, though. I don't know how to build them correctly ://
More complicated than I expected. Can either @JohanMabille or @martinRenou help me here?
I can force push and make a PR instead of you just reviewing my commits, but if you don't mind I think everything is basically here: https://github.com/jupyter-xeus/xeus-sqlite/commit/5767e00f168de0c6cfef0487442d0932a6148d7b
And the comments here: https://github.com/jupyter-xeus/xeus-sqlite/commit/9eef281c8ec9ac8da922ba7651d96d293c6f2678
I don't know how to make a CMake to build the docs. Thanks for the help! <3

**Comment by JohanMabille** [comment]
Yeah no worries. Let's catchup this afternoon after the dev meeting.
You need to update your git remote configuration, I guess that now your origin points to this repo instead of your fork.

**Comment by marimeireles** [comment]
Yep!
Thanks @JohanMabille =)

Would you like me to create a PR?

**Comment by marimeireles** [comment]
Hey @JohanMabille, I think I crossed all your boxes. Can we close this?
I still have to improve the tests though, but they're fully functional :)

**Comment by JohanMabille** [comment]
Yep definitely!
